### ISSUE TITLE
Channel Independent

### ISSUE THREAD

**Issue by MogicianXD** [plumprc/RTSF#1]
Do the current codes only implement RLinear-CI and RMLP-CI? 
As described by PatchTST, channel independence means the univariate time series share the same parameters, which is different from your channel individual setting.

**Comment by plumprc** [comment]
> Do the current codes only implement RLinear-CI and RMLP-CI? As described by PatchTST, channel independence means the univariate time series share the same parameters, which is different from your channel individual setting.

Thank you for your question. The current codes of RLinear and RMLP are satisfied the original definition of channel-independence in PatchTST. However, we notice that in the official releases of PatchTST and DLinear, they both remain a similar implementation where they can use multiple linear projection layers to output prediction for each channel. We will explain this in the future version.

Our channel individual setting is mainly for explaining why a single linear layer performs worse on some datasets with multiple periodic channels. An intriguing fact is that applying a nonlinear unit such as MLP with ReLU can achieve similar effects. So here are only the implementations of RLinear, RLinear-CI, and RMLP.

**Comment by MogicianXD** [comment]
Thanks! May revise your ##Limitations in README.md.

**Comment by Jay-ings** [comment]
Thanks for you research and implementation. It's been great help.

I have a same question, just for clarification.

When constructing RLinear with your code,
self.individual = True, then RLinear-CI
self.individual = False, then RLinear

Is the above understanding correct?

**Comment by plumprc** [comment]
> When constructing RLinear with your code, self.individual = True, then RLinear-CI self.individual = False, then RLinear
> 
> Is the above understanding correct?

Yes

**Comment by Jay-ings** [comment]
Thanks!
